Application\TaxiBundle\Entity\PointType:

    type: entity

    id:
        id:
            type: integer
            generator: { strategy: AUTO }

    fields:
        code: { type: string }

    indexes:
        code:
            columns: [code]
