sonata_admin:

    security:
        handler: sonata.admin.security.handler.role

    extensions:
        cmf_core.admin_extension.child:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\Model\ChildInterface
        cmf_core.admin_extension.publish_workflow.time_period:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\PublishWorkflow\PublishTimePeriodInterface
        cmf_core.admin_extension.publish_workflow.publishable:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\PublishWorkflow\PublishableInterface
        cmf_core.admin_extension.translatable:
            implements:
                - Symfony\Cmf\Bundle\CoreBundle\Translatable\TranslatableInterface
        cmf_menu.admin_extension.menu_node_referrers:
            implements:
                - Symfony\Cmf\Bundle\MenuBundle\Model\MenuNodeReferrersInterface
        cmf_routing.admin_extension.route_referrers:
            implements:
                - Symfony\Cmf\Component\Routing\RouteReferrersInterface
        cmf_seo.admin_extension:
            implements:
                - Symfony\Cmf\Bundle\SeoBundle\Model\SeoAwareInterface

    templates:
        # default global templates
        ajax:    SonataAdminBundle::ajax_layout.html.twig
        user_block: SandboxMainBundle:Admin:user_block.html.twig
        dashboard: ApplicationTaxiBundle:Admin:dashboard.html.twig
    dashboard:
        blocks:
            # display a dashboard block
#            - { position: left, type: sonata.admin.block.admin_list }
#            - { position: left, type: sonata_admin_doctrine_phpcr.tree_block }
        groups:
#            content:
#                label: Content
#                items:
#                    - cmf_content.admin
#                    - cmf_block.simple_admin
#                    - cmf_block.container_admin
#                    - cmf_block.reference_admin
#                    - cmf_block.action_admin
#                    - cmf_block.imagine.slideshow_admin
#                    - cmf_block.imagine.imagine_admin
#            routing:
#                label: URLs
#                items:
#                    - cmf_routing.route_admin
#                    - cmf_routing.redirect_route_admin
            menu:
                label: Menu
                items:
                    - cmf_menu.menu_admin
                    - cmf_menu.node_admin
            simplecms:
                label: CMS
                items:
                    - cmf_simple_cms.persistence.phpcr.admin.page

            orm:
                label: ORM
                items:
                    - taxi.admin.point_type
                    - taxi.admin.country
                    - taxi.admin.currency
                    - taxi.admin.point
                    - taxi.admin.route
                    - taxi.admin.transfer_type
                    - taxi.admin.transfer

            orders:
                label: Orders
                items:
                    - taxi.admin.order
                    - taxi.admin.order_state

            users:
                label: Users
                items:
                  - sonata.user.admin.user
                  - sonata.user.admin.group
