parameters:
#    application_taxi.example.class: Application\TaxiBundle\Example

services:
#    application_taxi.example:
#        class: %application_taxi.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]


    taxi.admin.point_type:
        class: Application\TaxiBundle\Admin\PointTypeAdmin
        arguments: [~, Application\TaxiBundle\Entity\PointType, SonataAdminBundle:CRUD]
        tags:
            - {name: sonata.admin, manager_type: orm, group: Point, label: PointType}
