parameters:
#    application_taxi.example.class: Application\TaxiBundle\Example

services:

    taxi.router.direction_finder.google:
        class: Application\TaxiBundle\Router\GoogleDirectionFinder
        arguments: [@buzz]

    taxi.points:
        class: Application\TaxiBundle\Router\PointManager
        arguments: [@doctrine.orm.entity_manager, @request]
        scope: request

    taxi.routes:
        class: Application\TaxiBundle\Router\RouteManager
        arguments: [@taxi.points, @doctrine.orm.entity_manager, @taxi.router.direction_finder.google]
        scope: request
